name:                opcon
version:             0.1.0.0
github:              "githubuser/nbrk"
license:             BSD3
author:              "Nikolay Burkov"
maintainer:          "nbrk@linklevel.net"
copyright:           "2019 Nikolay Burkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            DAG containers for dynamic, echeloned military hierarchies
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nbrk/opcon#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - mtl
    - graphite
    - hashable
    - graphviz
    - text

executables:
  opcon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opcon

